name: update_iplists

on:
  schedule:
    - cron: "30 05 * * *" # 05:30 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r github_actions_prereqs.txt

      - name: Execute github_actions_zscaler_ips.py Script
        run: python github_actions_zscaler_ips.py

      - name: Commit .rsc Files
        run: |
          #!/bin/bash
          NOW=$(date +"%m-%d-%Y %H:%M:%S")

          if ! grep -q "error" "zscaler-ips-required-v4.rsc" && ! grep -q "error" "zscaler-ips-recommended-v4.rsc" && ! grep -q "error" "zscaler-ips-required-v6.rsc" && ! grep -q "error" "zscaler-ips-recommended-v6.rsc"; then
            git config --local user.email "noreply@github.actions.bot"
            git config --local user.name "GitHub Actions"
            git add zscaler-ips-re*
            git status
            git commit -m "Refreshed - $NOW"
          fi

      - name: Push Changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
